name: Build and deploy Node.js app to Azure Web App - web-cms-i

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies and build
        run: |
          cd backend
          npm install
          npm run build
      - name: "Tar files"
        run: cd backend && tar -cf node-app.tar . && mv node-app.tar ..
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.tar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: "Untar files"
        run: "ls -at && pwd && tar -xf node-app.tar"
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "web-cms-i"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07E058DDADC9426B8145A8BE477C705D }}
          package: .
