# Dockerfile
FROM node:16
RUN apt-get update && apt-get install libvips-dev -y

ENV NODE_ENV=production
ENV DATABASE_CLIENT = postgres
ENV DATABASE_HOST = db.zynvbqjxkacssxrpfnmb.supabase.co
ENV DATABASE_PORT = 5432
ENV DATABASE_NAME = postgres
ENV DATABASE_USERNAME = postgres
ENV DATABASE_PASSWORD = hCqfw3JlSc3vuhE9

WORKDIR /opt/
COPY ./package.json ./yarn.lock ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn install
WORKDIR /opt/app
COPY ./ .
RUN yarn build
EXPOSE 1337
CMD ["yarn", "start"]