import {
  fifthContentBlock,
  firstContentBlock,
  fourthContentBlock,
  secondContentBlock,
  thirdContentBlock,
} from "@/assets";

export const content = [
  {
    id: 3,
    title: "Bezpiecznie przechowuj swoje pliki już dziś!",
    description:
      "Dzięki **Cloudrive** możesz mieć swobodny dostęp do swoich plików z każdego miejsca na świecie!",
    imageLeft: false,
    image: firstContentBlock,
    tags: [
      {
        id: 6,
        name: "Muzyka",
        backgroundColor: "#055F94",
        textColor: "#E6EFF4",
        icon: {
          data: {
            id: 2,
            attributes: {
              name: "tick",
              alternativeText: "tick",
              caption: "tick",
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_9dc16a78b8",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_9dc16a78b8.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T15:34:07.006Z",
              updatedAt: "2023-04-24T15:35:38.146Z",
            },
          },
        },
      },
      {
        id: 7,
        name: "Dokumenty",
        backgroundColor: "#055F94",
        textColor: "#E6EFF4",
        icon: {
          data: {
            id: 2,
            attributes: {
              name: "tick",
              alternativeText: "tick",
              caption: "tick",
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_9dc16a78b8",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_9dc16a78b8.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T15:34:07.006Z",
              updatedAt: "2023-04-24T15:35:38.146Z",
            },
          },
        },
      },
      {
        id: 8,
        name: "Filmy",
        backgroundColor: "#055F94",
        textColor: "#E6EFF4",
        icon: {
          data: {
            id: 2,
            attributes: {
              name: "tick",
              alternativeText: "tick",
              caption: "tick",
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_9dc16a78b8",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_9dc16a78b8.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T15:34:07.006Z",
              updatedAt: "2023-04-24T15:35:38.146Z",
            },
          },
        },
      },
      {
        id: 9,
        name: "Wiele innych",
        backgroundColor: "#055F94",
        textColor: "#E6EFF4",
        icon: {
          data: {
            id: 2,
            attributes: {
              name: "tick",
              alternativeText: "tick",
              caption: "tick",
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_9dc16a78b8",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_9dc16a78b8.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T15:34:07.006Z",
              updatedAt: "2023-04-24T15:35:38.146Z",
            },
          },
        },
      },
    ],
    button: {
      id: 6,
      content: "Czytaj dalej",
      hoverColor: null,
      backgroundColor: "white",
      textColor: "#055F94",
      link: "/",
    },
  },
  {
    id: 4,
    title: "Gdziekolwiek potrzebujesz",
    description:
      "Dostęp do dysku w Cloudrive masz z każdego miejsca na świecie! Wystarczy dostęp do internetu.",
    imageLeft: true,
    image: secondContentBlock,
    tags: [
      {
        id: 10,
        name: "Telefon",
        backgroundColor: "#F4E7CC",
        textColor: "#A26D02",
        icon: {
          data: {
            id: 5,
            attributes: {
              name: "tick-2.svg",
              alternativeText: null,
              caption: null,
              width: 12,
              height: 12,
              formats: null,
              hash: "tick_2_5cbfb396b4",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.27,
              url: "/uploads/tick_2_5cbfb396b4.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:05:36.838Z",
              updatedAt: "2023-04-24T16:05:36.838Z",
            },
          },
        },
      },
      {
        id: 11,
        name: "Komputer",
        backgroundColor: "#F4E7CC",
        textColor: "#A26D02",
        icon: {
          data: {
            id: 5,
            attributes: {
              name: "tick-2.svg",
              alternativeText: null,
              caption: null,
              width: 12,
              height: 12,
              formats: null,
              hash: "tick_2_5cbfb396b4",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.27,
              url: "/uploads/tick_2_5cbfb396b4.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:05:36.838Z",
              updatedAt: "2023-04-24T16:05:36.838Z",
            },
          },
        },
      },
      {
        id: 12,
        name: "Tablet",
        backgroundColor: "#F4E7CC",
        textColor: "#A26D02",
        icon: {
          data: {
            id: 5,
            attributes: {
              name: "tick-2.svg",
              alternativeText: null,
              caption: null,
              width: 12,
              height: 12,
              formats: null,
              hash: "tick_2_5cbfb396b4",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.27,
              url: "/uploads/tick_2_5cbfb396b4.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:05:36.838Z",
              updatedAt: "2023-04-24T16:05:36.838Z",
            },
          },
        },
      },
    ],
    button: null,
  },
  {
    id: 5,
    title: "Cenimy bezpieczeństwo",
    description:
      "Twoje pliki są bezpieczne w Cloudrive dzięki zastosowaniu najnowszych technologii",
    imageLeft: false,
    image: thirdContentBlock,
    tags: [],
    button: null,
  },
  {
    id: 6,
    title: "Gwarancja zadowolenia",
    description:
      "Nasz wszechstronny system spełni oczekiwania każdego użytkownika. Już dzisiaj załóż konto i przekonaj się sam.",
    imageLeft: true,
    image: fourthContentBlock,
    tags: [
      {
        id: 13,
        name: "Udostępniamy",
        backgroundColor: "#28666E",
        textColor: "#EAF0F1",
        icon: {
          data: {
            id: 8,
            attributes: {
              name: "tick-3.svg",
              alternativeText: null,
              caption: null,
              width: 10,
              height: 11,
              formats: null,
              hash: "tick_3_628d74ddc0",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.29,
              url: "/uploads/tick_3_628d74ddc0.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:35:05.391Z",
              updatedAt: "2023-04-24T16:35:05.391Z",
            },
          },
        },
      },
      {
        id: 14,
        name: "Przechowywanie",
        backgroundColor: "#28666E",
        textColor: "#EAF0F1",
        icon: {
          data: {
            id: 8,
            attributes: {
              name: "tick-3.svg",
              alternativeText: null,
              caption: null,
              width: 10,
              height: 11,
              formats: null,
              hash: "tick_3_628d74ddc0",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.29,
              url: "/uploads/tick_3_628d74ddc0.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:35:05.391Z",
              updatedAt: "2023-04-24T16:35:05.391Z",
            },
          },
        },
      },
      {
        id: 15,
        name: "Edycja",
        backgroundColor: "#28666E",
        textColor: "#EAF0F1",
        icon: {
          data: {
            id: 8,
            attributes: {
              name: "tick-3.svg",
              alternativeText: null,
              caption: null,
              width: 10,
              height: 11,
              formats: null,
              hash: "tick_3_628d74ddc0",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.29,
              url: "/uploads/tick_3_628d74ddc0.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:35:05.391Z",
              updatedAt: "2023-04-24T16:35:05.391Z",
            },
          },
        },
      },
    ],
    button: null,
  },
  {
    id: 7,
    title: "Prywatność",
    description:
      "Tylko Ty masz władzę nad tym, kto widzi Twoje pliki i zasoby. W każdej chwili możesz zdecydować kto ma dostęp do Twojego dysku.",
    imageLeft: false,
    image: fifthContentBlock,
    tags: [
      {
        id: 16,
        name: "Przechowywanie",
        backgroundColor: "#E6EEE6",
        textColor: "#005108",
        icon: {
          data: {
            id: 10,
            attributes: {
              name: "tick-4.svg",
              alternativeText: null,
              caption: null,
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_4_9f28efa8ae",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_4_9f28efa8ae.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:48:16.412Z",
              updatedAt: "2023-04-24T16:48:16.412Z",
            },
          },
        },
      },
      {
        id: 17,
        name: "Edycja",
        backgroundColor: "#E6EEE6",
        textColor: "#005108",
        icon: {
          data: {
            id: 10,
            attributes: {
              name: "tick-4.svg",
              alternativeText: null,
              caption: null,
              width: 12,
              height: 13,
              formats: null,
              hash: "tick_4_9f28efa8ae",
              ext: ".svg",
              mime: "image/svg+xml",
              size: 0.37,
              url: "/uploads/tick_4_9f28efa8ae.svg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2023-04-24T16:48:16.412Z",
              updatedAt: "2023-04-24T16:48:16.412Z",
            },
          },
        },
      },
    ],
  },
];
